name: di
version: 1.0.0
authors:
- Vojta Jina <vojta.jina@gmail.com>
- Pavel Jbanov <pavelgj@gmail.com>
description: Dependency Injection framework
homepage: https://github.com/angular/di.dart
environment:
  sdk: '>=0.8.10'
dependencies:
  analyzer: '>=0.13.0 <0.14.0'
  barback: '>=0.13.0 <0.14.0'
  code_transformers: '>=0.1.3 <0.2.0'
  path: ">=1.2.0 <2.0.0"
dev_dependencies:
  benchmark_harness: ">=1.0.4 <2.0.0"
  browser: ">=0.10.0 <0.11.0"
  guinness: ">=0.1.7 <0.2.0"

transformers:
- di:
    injectable_annotations: di.tests.InjectableTest
