name: di
description: A prototype of Dependency Injection framework.
version: 0.0.20
author: "Vojta Jina <vojta.jina@gmail.com>"
homepage: https://github.com/angular/di.dart

dependencies:
  analyzer_experimental: any

dev_dependencies:
  unittest: any
